"""
Django settings for deploy project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3tb8&e-onk23r=gc)e4!6o()=f9&7i%(&2tae@cq)mto@1^c%1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ "http://localhost:3002", 'localhost', '127.0.0.1', "*"]

APPEND_SLASH = False 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
     'corsheaders',
    'apps.users',
    'apps.deployments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deploy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deploy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'deploydb',  # Cambia si usas otra base de datos
#         'USER': 'deployuser',
#         'PASSWORD': 'reymanuel010899',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

# AWS Configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_DEFAULT_REGION = os.getenv('AWS_DEFAULT_REGION', 'us-east-1')

# AWS ECS Configuration
AWS_ECS_CLUSTER_NAME = os.getenv('AWS_ECS_CLUSTER_NAME', 'default')
AWS_ECS_EXECUTION_ROLE_ARN = os.getenv('AWS_ECS_EXECUTION_ROLE_ARN')
AWS_ECS_TASK_ROLE_ARN = os.getenv('AWS_ECS_TASK_ROLE_ARN')
AWS_ECS_AUTOSCALING_ROLE_ARN = os.getenv('AWS_ECS_AUTOSCALING_ROLE_ARN')
AWS_ECS_SUBNETS = os.getenv('AWS_ECS_SUBNETS', '').split(',')
AWS_ECS_SECURITY_GROUPS = os.getenv('AWS_ECS_SECURITY_GROUPS', '').split(',')
    
    # Auto-scaling Configuration
AWS_AUTOSCALING_DEFAULT_COOLDOWN = int(os.getenv('AWS_AUTOSCALING_DEFAULT_COOLDOWN', '60'))
AWS_AUTOSCALING_DEFAULT_TARGET_CPU = int(os.getenv('AWS_AUTOSCALING_DEFAULT_TARGET_CPU', '75'))
AWS_AUTOSCALING_DEFAULT_TARGET_MEMORY = int(os.getenv('AWS_AUTOSCALING_DEFAULT_TARGET_MEMORY', '75'))
    
    # AWS ECR Configuration
AWS_ECR_REPOSITORY_PREFIX = os.getenv('AWS_ECR_REPOSITORY_PREFIX')

    # Logging Configuration
AWS_CLOUDWATCH_LOG_GROUP = os.getenv('AWS_CLOUDWATCH_LOG_GROUP', '/ecs/deployments')
AWS_CLOUDWATCH_LOG_STREAM_PREFIX = os.getenv('AWS_CLOUDWATCH_LOG_STREAM_PREFIX', 'deployment')

# Configure boto3
import boto3
boto3.setup_default_session(
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_DEFAULT_REGION
)

"""
Django settings for deploy project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3tb8&e-onk23r=gc)e4!6o()=f9&7i%(&2tae@cq)mto@1^c%1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ "http://localhost:3002", 'localhost', '127.0.0.1', "*"]

APPEND_SLASH = False 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
     'corsheaders',
    'apps.users',
    'apps.deployments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deploy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deploy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'deploydb',  # Cambia si usas otra base de datos
#         'USER': 'deployuser',
#         'PASSWORD': 'reymanuel010899',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

# AWS Configuration
try:
    from .local_settings import *
except ImportError:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', 'us-east-1')
    
    # AWS ECS Configuration
    AWS_ECS_CLUSTER_NAME = os.environ.get('AWS_ECS_CLUSTER_NAME', 'default')
    AWS_ECS_EXECUTION_ROLE_ARN = os.environ.get('AWS_ECS_EXECUTION_ROLE_ARN')
    AWS_ECS_TASK_ROLE_ARN = os.environ.get('AWS_ECS_TASK_ROLE_ARN')
    AWS_ECS_AUTOSCALING_ROLE_ARN = os.environ.get('AWS_ECS_AUTOSCALING_ROLE_ARN')
    AWS_ECS_SUBNETS = os.environ.get('AWS_ECS_SUBNETS', '').split(',')
    AWS_ECS_SECURITY_GROUPS = os.environ.get('AWS_ECS_SECURITY_GROUPS', '').split(',')
    
    # Auto-scaling Configuration
    AWS_AUTOSCALING_DEFAULT_COOLDOWN = int(os.environ.get('AWS_AUTOSCALING_DEFAULT_COOLDOWN', '60'))
    AWS_AUTOSCALING_DEFAULT_TARGET_CPU = int(os.environ.get('AWS_AUTOSCALING_DEFAULT_TARGET_CPU', '75'))
    AWS_AUTOSCALING_DEFAULT_TARGET_MEMORY = int(os.environ.get('AWS_AUTOSCALING_DEFAULT_TARGET_MEMORY', '75'))
    
    # AWS ECR Configuration
    AWS_ECR_REPOSITORY_PREFIX = os.environ.get('AWS_ECR_REPOSITORY_PREFIX')
    
    # Logging Configuration
    AWS_CLOUDWATCH_LOG_GROUP = os.environ.get('AWS_CLOUDWATCH_LOG_GROUP', '/ecs/deployments')
    AWS_CLOUDWATCH_LOG_STREAM_PREFIX = os.environ.get('AWS_CLOUDWATCH_LOG_STREAM_PREFIX', 'deployment')

# Configure boto3
import boto3
boto3.setup_default_session(
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_DEFAULT_REGION
)
