# Generated by Django 5.2.3 on 2025-06-16 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_task_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_cluster_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_service_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_region', models.CharField(default='us-east-1', max_length=50)),
                ('container_name', models.CharField(default='app', max_length=255)),
                ('command', models.JSONField(blank=True, default=list, help_text='Command to run in the container (overrides Dockerfile CMD)')),
                ('entrypoint', models.JSONField(blank=True, default=list, help_text='Entrypoint for the container (overrides Dockerfile ENTRYPOINT)')),
                ('cpu_units', models.IntegerField(help_text='CPU units (256 = 0.25 vCPU, 1024 = 1 vCPU)', validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('memory_mb', models.IntegerField(help_text='Memory in MB', validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(8192)])),
                ('port_mappings', models.JSONField(default=list, help_text="List of port mappings in format [{'containerPort': 80, 'hostPort': 80, 'protocol': 'tcp'}]")),
                ('network_mode', models.CharField(choices=[('awsvpc', 'awsvpc'), ('bridge', 'bridge'), ('host', 'host'), ('none', 'none')], default='awsvpc', max_length=20)),
                ('environment_variables', models.JSONField(default=dict, help_text='Environment variables for the container')),
                ('secrets', models.JSONField(default=dict, help_text='Secrets to be retrieved from AWS Secrets Manager')),
                ('volumes', models.JSONField(default=list, help_text="List of volume mounts in format [{'name': 'my-volume', 'hostPath': '/data', 'containerPath': '/app/data'}]")),
                ('health_check', models.JSONField(default=dict, help_text='Health check configuration for the container')),
                ('log_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('log_stream_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('desired_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('error', 'Error'), ('warning', 'Warning'), ('success', 'Success')], max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('aws', 'AWS'), ('container', 'Container'), ('user', 'User')], default='system', max_length=50)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deployments.deployment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_utilization', models.FloatField(help_text='CPU utilization percentage')),
                ('memory_utilization', models.FloatField(help_text='Memory utilization percentage')),
                ('network_bytes_in', models.BigIntegerField(help_text='Network bytes received')),
                ('network_bytes_out', models.BigIntegerField(help_text='Network bytes sent')),
                ('running_tasks', models.IntegerField(default=0, help_text='Number of running tasks')),
                ('pending_tasks', models.IntegerField(default=0, help_text='Number of pending tasks')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='deployments.deployment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(default='latest', max_length=100)),
                ('registry_url', models.URLField(help_text='URL del registro Docker (ej: docker.io, ecr.amazonaws.com)', max_length=500)),
                ('repository_name', models.CharField(help_text='Nombre del repositorio en el registro', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'tag', 'registry_url')},
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='docker_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='deployments.dockerimage'),
        ),
    ]
