# Generated by Django 5.2.3 on 2025-07-07 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('docker_images', models.JSONField(blank=True, default=list, help_text="List of Docker images in format [{'name': 'image_name', 'tag': 'latest', 'port': 80, 'registry_url': 'docker.io', 'repository_name': 'my_repo'}]")),
                ('cpu_units', models.IntegerField(help_text='CPU units (256 = 0.25 vCPU, 1024 = 1 vCPU)', validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('memory_mb', models.IntegerField(help_text='Memory in MB', validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(8192)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_task_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_cluster_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_service_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_region', models.CharField(default='us-east-1', max_length=50)),
                ('auto_scaling_enabled', models.BooleanField(default=False)),
                ('scaling_policies', models.JSONField(blank=True, default=list, help_text="List of scaling policies in format [{'type': 'cpu|memory', 'target_value': 75, 'scale_in_cooldown': 60, 'scale_out_cooldown': 60}]", null=True)),
                ('desired_count', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_count', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_count', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('port_mappings', models.JSONField(blank=True, default=list, help_text="List of port mappings in format [{'containerPort': 80, 'hostPort': 80, 'protocol': 'tcp'}]", null=True)),
                ('environment_variables', models.JSONField(blank=True, default=dict, help_text='Environment variables for the container', null=True)),
                ('secrets', models.JSONField(blank=True, default=dict, help_text='Secrets to be retrieved from AWS Secrets Manager', null=True)),
                ('network_mode', models.CharField(choices=[('awsvpc', 'awsvpc'), ('bridge', 'bridge'), ('host', 'host'), ('none', 'none')], default='awsvpc', max_length=20)),
                ('load_balancer', models.BooleanField(default=False, help_text='Whether to attach a load balancer to the service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(default='latest', max_length=100)),
                ('port', models.IntegerField(blank=True, help_text='Puerto expuesto por la imagen Docker', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('registry_url', models.URLField(blank=True, help_text='URL del registro Docker (ej: docker.io, ecr.amazonaws.com)', max_length=500, null=True)),
                ('repository_name', models.CharField(blank=True, help_text='Nombre del repositorio en el registro', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'tag', 'registry_url')},
            },
        ),
    ]
