# Generated by Django 5.2.3 on 2025-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='regions',
            field=models.JSONField(blank=True, default=list, help_text="List of Docker images in format [{'name': 'image_name', 'tag': 'latest', 'port': 80, 'registry_url': 'docker.io', 'repository_name': 'my_repo'}]"),
        ),
    ]
