# Generated by Django 5.2.3 on 2025-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='auto_scaling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='scaling_policies',
            field=models.JSONField(default=list, help_text="List of scaling policies in format [{'type': 'cpu|memory', 'target_value': 75, 'scale_in_cooldown': 60, 'scale_out_cooldown': 60}]"),
        ),
        migrations.AddField(
            model_name='deployment',
            name='scheduled_actions',
            field=models.JSONField(default=list, help_text="List of scheduled scaling actions in format [{'schedule': 'cron(0 8 * * ? *)', 'min_capacity': 2, 'max_capacity': 10}]"),
        ),
        migrations.AddField(
            model_name='deployment',
            name='target_tracking_policies',
            field=models.JSONField(default=list, help_text="List of target tracking policies in format [{'type': 'CPUUtilization|MemoryUtilization', 'target_value': 75}]"),
        ),
    ]
