# Generated by Django 5.2.3 on 2025-06-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deployment_auto_scaling_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='docker_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='deployments.dockerimage'),
        ),
    ]
