# Generated by Django 5.2.3 on 2025-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deployment_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
