# Generated by Django 5.2.3 on 2025-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_deployment_deployment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='service',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
