# Generated by Django 5.2.3 on 2025-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_alter_deployment_docker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimage',
            name='registry_url',
            field=models.URLField(blank=True, help_text='URL del registro Docker (ej: docker.io, ecr.amazonaws.com)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nombre del repositorio en el registro', max_length=255, null=True),
        ),
    ]
