# Generated by Django 4.2.27 on 2026-02-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='domain_name',
            field=models.CharField(blank=True, help_text='Domain name for the deployment', max_length=255, null=True),
        ),
    ]
