# Generated by Django 5.2.3 on 2025-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_alter_dockerimage_registry_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='health_check',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='log_group_name',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='log_stream_prefix',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='scheduled_actions',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='target_tracking_policies',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='volumes',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='docker_image',
        ),
        migrations.AddField(
            model_name='deployment',
            name='docker_image',
            field=models.ManyToManyField(blank=True, null=True, related_name='deployments', to='deployments.dockerimage'),
        ),
    ]
