# Generated by Django 5.2.3 on 2025-06-18 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_remove_deployment_health_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentmetrics',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='command',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='entrypoint',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='network_mode',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='desired_count',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='environment_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Environment variables for the container', null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='max_count',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='min_count',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='port_mappings',
            field=models.JSONField(blank=True, default=list, help_text="List of port mappings in format [{'containerPort': 80, 'hostPort': 80, 'protocol': 'tcp'}]", null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='scaling_policies',
            field=models.JSONField(blank=True, default=list, help_text="List of scaling policies in format [{'type': 'cpu|memory', 'target_value': 75, 'scale_in_cooldown': 60, 'scale_out_cooldown': 60}]", null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='secrets',
            field=models.JSONField(blank=True, default=dict, help_text='Secrets to be retrieved from AWS Secrets Manager', null=True),
        ),
        migrations.DeleteModel(
            name='DeploymentLog',
        ),
        migrations.DeleteModel(
            name='DeploymentMetrics',
        ),
    ]
