# Generated by Django 4.2.19 on 2026-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deployment_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='aws_cluster_arn',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='aws_service_arn',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
