# Generated by Django 4.2.19 on 2026-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_alter_deployment_aws_cluster_arn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='aws_cluster_arn',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='aws_service_arn',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
