# Generated by Django 5.2.3 on 2025-06-19 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_remove_deploymentmetrics_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='port',
            field=models.IntegerField(blank=True, help_text='Puerto expuesto por la imagen Docker', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
