# Generated by Django 4.2.19 on 2026-04-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_alter_deployment_aws_cluster_arn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='lambda_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
