# Generated by Django 5.2.3 on 2025-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_dockerimage_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='docker_image',
        ),
        migrations.AddField(
            model_name='deployment',
            name='docker_images',
            field=models.JSONField(blank=True, default=list, help_text="List of Docker images in format [{'name': 'image_name', 'tag': 'latest', 'port': 80, 'registry_url': 'docker.io', 'repository_name': 'my_repo'}]"),
        ),
    ]
