# Generated by Django 5.2.3 on 2025-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_remove_deployment_docker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='network_mode',
            field=models.CharField(choices=[('awsvpc', 'awsvpc'), ('bridge', 'bridge'), ('host', 'host'), ('none', 'none')], default='awsvpc', max_length=20),
        ),
    ]
