# Generated by Django 4.2.19 on 2026-04-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_deployment_lambda_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='region_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of {region, url} per deployed region'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
