# Generated by Django 5.2.3 on 2025-06-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_deployment_network_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='load_balancer',
            field=models.BooleanField(default=False, help_text='Whether to attach a load balancer to the service'),
        ),
    ]
