AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Cluster usando VPC y subnets existentes

Parameters:
  VPCId:
    Type: String
    Default: vpc-0d1125fbea39e69f4

  PublicSubnetId:
    Type: String
    Default: subnet-08739eb429d2fabe8

  PublicSubnetId2:
    Type: String
    Description: Segunda Subred Publica para el Load Balancer (en una AZ diferente)
    Default: subnet-0992517bfc7a9454c 

  ECSServiceName:
    Type: String
    Default: ecs-service

  PrivateSubnetId:
    Type: String
    Default: subnet-02ad64779efe7a82d

  ClusterName:
    Type: String
    Description: Nombre de la definición de tarea

  TaskName:
    Type: String
    Description: Nombre de la definición de tarea

  Image1:
    Type: String
    Description: Imagen contenedor 1

  Image2:
    Type: String
    Description: Imagen contenedor 2

  Image3:
    Type: String
    Description: Imagen contenedor 3

  Cpu:
    Type: String
    AllowedValues: ['256', '512', '1024', '2048', '4096']
    Description: CPU para la tarea

  # Memory for the task in MB
  CpuContainer1:
    Type: String
    AllowedValues: ['128','256', '512', '1024', '2048', '4096']
    Description: CPU (en unidades) para el contenedor 1

  CpuContainer2:
    Type: String
    AllowedValues: ['128','256', '512', '1024', '2048', '4096']
    Description: CPU (en unidades) para el contenedor 2 

  CpuContainer3:
    Type: String
    AllowedValues: ['128','256', '512', '1024', '2048', '4096']
    Description: CPU (en unidades) para el contenedor 3

  MemoryContainer1:
    Type: String
    AllowedValues: ['128','256', '512', '1024', '2048', '3072', '4096', '5120', '6144', '7168', '8192']
    Description: RAM (en MB) para el contenedor 1

  MemoryContainer2:
    Type: String
    AllowedValues: ['128','256', '512', '1024', '2048', '3072', '4096', '5120', '6144', '7168', '8192']
    Description: RAM (en MB) para el contenedor 2

  MemoryContainer3:
    Type: String
    AllowedValues: ['128','256', '512', '1024', '2048', '3072', '4096', '5120', '6144', '7168', '8192']
    Description: RAM (en MB) para el contenedor 2

  Memory:
    Type: String
    AllowedValues: ['512', '1024', '2048', '3072', '4096', '5120', '6144', '7168', '8192']
    Description: RAM (en MB) para la tarea

  App1Port:
    Type: Number
    Description: Puerto para el contenedor 1

  App2Port:
    Type: Number
    Description: Puerto para el contenedor 2

  App3Port:
    Type: Number
    Description: Puerto para el contenedor 3

  DatabaseEngine:
    Type: String
    Default: MYSQL
    AllowedValues:
      - POSTGRES
      - MYSQL
      - MARIADB
      - ORACLE-SE2      # Oracle Standard Edition Two
      - ORACLE-EE       # Oracle Enterprise Edition
      - SQLSERVER-EE    # SQL Server Enterprise Edition
      - SQLSERVER-SE    # SQL Server Standard Edition
      - SQLSERVER-EX    # SQL Server Express Edition
      - SQLSERVER-WEB   # SQL Server Web Edition
      - AURORA          # Aurora MySQL-compatible
      - AURORA-MYSQL    # Aurora MySQL (nuevo identificador)
      - AURORA-POSTGRESQL # Aurora PostgreSQL

    Description: Tipo de motor de base de datos

  DatabaseName:
    Type: String
    Description: Nombre de la base de datos

  DatabaseUser:
    Type: String
    Description: Usuario de la base de datos

  DatabasePassword:
    Type: String
    Description: Contraseña del usuario de la base de datos

  DatabaseRootPassword:
    Type: String
    Description: Contraseña del usuario de la base de datos

  DatabaseHost:
    Type: String
    Description: Contraseña del root de la base de datos

  DatabasePort:
    Type: String
    Description: Puerto de la base de datos

  LoadBalancerEnabled:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Habilitar Load Balancer

  AutoScalingEnabled:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Habilitar Auto Scaling

  MinCapacity:
    Type: Number
    Default: 1
    Description: Capacidad mínima para Auto Scaling

  MaxCapacity:
    Type: Number
    Default: 3
    Description: Capacidad máxima para Auto Scaling

  DesiredTaskCount:
    Type: Number
    Default: 1
    Description: Capacidad máxima para Auto Scaling
    
Conditions:
  LoadBalancerEnabledCondition: !Equals [!Ref LoadBalancerEnabled, "true"]
  AutoScalingEnabledCondition: !Equals [!Ref AutoScalingEnabled, "true"]
  LoadBalancerDisabledCondition: !Not [!Condition LoadBalancerEnabledCondition]

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup  
    Properties:
        GroupDescription: Allow HTTP Traffic
        VpcId: !Ref VPCId
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0

  ECSLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Sub "/ecs/${ClusterName}"
        RetentionInDays: 7

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${ClusterName}:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${ClusterName}"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: mi-task-def
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
      - Name: WebServer  # backend
        Image: !Ref Image1
        Essential: true
        Cpu: !Ref CpuContainer1
        Memory: !Ref MemoryContainer1
        PortMappings:
          - ContainerPort: !Ref App1Port  # ej: 3000
            Protocol: tcp
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Sub "/ecs/${ClusterName}"
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: "webserver"
            
        Environment:
          - Name: !Sub "${DatabaseEngine}_HOST"
            Value: DataBase
          - Name: !Sub "${DatabaseEngine}_PORT"
            Value: !Ref DatabasePort
          - Name: !Sub "${DatabaseEngine}_DATABASE"
            Value: !Ref DatabaseName
          - Name: !Sub "${DatabaseEngine}_USER"
            Value: !Ref DatabaseUser
          - Name: !Sub "${DatabaseEngine}_PASSWORD"
            Value: !Ref DatabasePassword
          - Name: !Sub "${DatabaseEngine}_ROOT_PASSWORD"
            Value: !Ref DatabaseRootPassword

      - Name: Website  # frontend
        Image: !Ref Image2
        Essential: true
        Cpu: !Ref CpuContainer2
        Memory: !Ref MemoryContainer2
        PortMappings:
          - ContainerPort: !Ref App2Port # ej: 80
            hostPort: !Ref App2Port
            Protocol: tcp
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Sub "/ecs/${ClusterName}"
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: "website"

      - Name: DataBase
        Image: !Ref Image3
        Essential: true
        Cpu: !Ref CpuContainer3
        Memory: !Ref MemoryContainer3
        PortMappings:
          - ContainerPort: !Ref App3Port  # ej: 3306
            Protocol: tcp
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Sub "/ecs/${ClusterName}"
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: "database"
        
        Environment:
          - Name: !Sub "${DatabaseEngine}_HOST"
            Value: DataBase
          - Name: !Sub "${DatabaseEngine}_PORT"
            Value: !Ref DatabasePort
          - Name: !Sub "${DatabaseEngine}_DATABASE"
            Value: !Ref DatabaseName
          - Name: !Sub "${DatabaseEngine}_USER"
            Value: !Ref DatabaseUser
          - Name: !Sub "${DatabaseEngine}_PASSWORD"
            Value: !Ref DatabasePassword
          - Name: !Sub "${DatabaseEngine}_ROOT_PASSWORD"
            Value: !Ref DatabaseRootPassword

  ECSALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Condition: LoadBalancerEnabledCondition
    Properties:
      Subnets:
        - !Ref PublicSubnetId
        - !Ref PublicSubnetId2 
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Scheme: internet-facing

  ECSALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: LoadBalancerEnabledCondition
    Properties:
      LoadBalancerArn: !Ref ECSALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup


  ECSServiceWithLB:
    Type: AWS::ECS::Service
    Condition: LoadBalancerEnabledCondition
    DependsOn: ECSALBListener
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: !Ref MinCapacity
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnetId
          SecurityGroups:
            - !Ref InstanceSecurityGroup
      LoadBalancers:
        - ContainerName: WebServer
          ContainerPort: !Ref App1Port
          TargetGroupArn: !Ref ECSTargetGroup

  ECSServiceNoLB:
    Type: AWS::ECS::Service
    Condition: LoadBalancerDisabledCondition
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredTaskCount
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnetId
          SecurityGroups:
            - !Ref InstanceSecurityGroup


  ECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: LoadBalancerEnabledCondition
    Properties:
      VpcId: !Ref VPCId
      Protocol: HTTP
      Port: !Ref App1Port
      TargetType: ip

  ECSAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: AutoScalingEnabledCondition
    Properties:
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      ResourceId: !Sub "service/${ECSCluster}/${ECSServiceName}"
      RoleARN: !GetAtt ECSExecutionRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ECSAutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: AutoScalingEnabledCondition
    Properties:
      PolicyName: ECSAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 85.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

Outputs:
  ServiceCluster:
    Description: Nombre del cluster ECS creado
    Value: !Ref ECSCluster

  ECSServiceName:
    Description: Nombre del servicio ECS creado
    Value: !Ref ECSServiceName

  LoadBalancerURL:
    Description: URL del Load Balancer (si está habilitado)
    Value: !If [LoadBalancerEnabledCondition, !GetAtt ECSALB.DNSName, "Load Balancer no habilitado"]
    Condition: LoadBalancerEnabledCondition 